import type { ClientConfig } from "../types";

export const agapeTurfClient: ClientConfig = {
  slug: "agape-turf",
  companyName: "Agape Turf",
  brandName: "AGAPE TURF",
  legalName: "Agape Turf LLC",
  serviceLabel: "Artificial Turf",
  positioning: "Phoenix-area installer offering artificial turf, putting greens, and custom landscape design across the Valley.",
  website: "https://agapeturf.com/",
  logoPath: "/images/agape-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(623) 388-3758",
  email: "agapeturf@hotmail.com",
  navLinks: ["Artificial Turf", "Putting Greens", "Landscape Design", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Putting Greens",
    "Custom Landscape Design",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Putting Green",
    "Front Yard",
    "Back Yard",
    "Full Landscaping",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Putting Green": [4000, 11000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Full Landscaping": "review",
    Other: "review",
  },
  estimatePrefix: "AG",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#183820",
    primarySoft: "#e7f1e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should Agape Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Agape Turf.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a Agape Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Agape Turf follows up with measurements, options, and final pricing",
    ],
  },
};
