import type { ClientConfig } from "../types";

export const allValleyTurfClient: ClientConfig = {
  slug: "all-valley-turf",
  companyName: "All Valley Turf",
  brandName: "ALL VALLEY TURF",
  legalName: "All Valley Turf",
  serviceLabel: "Artificial Turf & Pavers",
  positioning: "Scottsdale-based artificial turf and paver installer offering durable outdoor upgrades and broader landscaping value.",
  website: "https://allvalleyturf.com/",
  logoPath: "/images/all-valley-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 418-0424",
  email: "info@allvalleyturf.com",
  navLinks: ["Artificial Turf", "Pavers", "Landscaping", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Pavers",
    "Landscaping",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Full Landscaping",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Full Landscaping": "review",
    Other: "review",
  },
  estimatePrefix: "AV",
  colors: {
    primary: "#2f8a3a",
    primaryDark: "#143a1c",
    primarySoft: "#e9f4e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf & Pavers Project Preview",
    contactPrompt: "Where should All Valley Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing All Valley Turf.",
    specialistLabel: "Artificial Turf & Pavers Specialists",
    reviewRequired: "This selection needs a All Valley Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "All Valley Turf follows up with measurements, options, and final pricing",
    ],
  },
};
