import type { ClientConfig } from "../types";

export const apexTurfClient: ClientConfig = {
  slug: "apex-turf",
  companyName: "Apex Turf",
  brandName: "APEX TURF",
  legalName: "Apex Turf",
  serviceLabel: "Artificial Grass",
  positioning: "Phoenix-area artificial turf installer with free quotes.",
  website: "https://apexturfaz.com/",
  logoPath: "/images/apex-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 935-6228",
  email: "quotes@apexturfaz.com",
  navLinks: ["Artificial Grass", "Pet Turf", "Putting Greens", "Pavers", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Greens",
    "Pavers",
    "Backyard Turf",
    "Front Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "AT",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#183820",
    primarySoft: "#e7f1e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 54,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should Apex Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Apex Turf.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs an Apex Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Apex Turf follows up with measurements, options, and final pricing",
    ],
  },
};
