import type { ClientConfig } from "../types";

export const arizonaLuxuryLawnsClient: ClientConfig = {
  slug: "arizona-luxury-lawns",
  companyName: "Arizona Luxury Lawns",
  brandName: "ARIZONA LUXURY LAWNS",
  legalName: "Arizona Luxury Lawns",
  serviceLabel: "Artificial Grass",
  positioning: "Scottsdale artificial turf installer focused on durable, long-lasting premium grass installations.",
  website: "https://arizonaluxurylawns.com/",
  logoPath: "/images/arizona-luxury-lawns-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 991-0196",
  email: "info@arizonaluxurylawns.com",
  navLinks: ["Artificial Grass", "Putting Greens", "Pet Turf", "Service Areas", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass",
    "Putting Greens",
    "Pet Turf",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Putting Green",
    "Pet Turf",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Putting Green": [4000, 11000],
    "Pet Turf": [5500, 15500],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "AL",
  colors: {
    primary: "#2f8151",
    primaryDark: "#173d28",
    primarySoft: "#e8f1ea",
    accent: "#c6a24a",
    accentDark: "#8c6f24",
  },
  pdfLogo: {
    background: "dark",
    width: 150,
    height: 42,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Arizona Luxury Lawns prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Arizona Luxury Lawns.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Arizona Luxury Lawns review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Arizona Luxury Lawns follows up with measurements, options, and final pricing",
    ],
  },
};
