import type { ClientConfig } from "../types";

export const artificialGrassSuperstoreClient: ClientConfig = {
  slug: "artificial-grass-superstore",
  companyName: "Artificial Grass Superstore",
  brandName: "ARTIFICIAL GRASS SUPERSTORE",
  legalName: "Artificial Grass Superstore",
  serviceLabel: "Artificial Grass",
  positioning: "Phoenix artificial grass installer and supplier with long-tenure trust messaging and a broad residential-to-commercial turf pitch.",
  website: "https://www.artificialgrasssuperstore.com/",
  logoPath: "/images/artificial-grass-superstore-logo.svg",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 726-2411",
  email: "info@artificialgrasssuperstore.com",
  navLinks: ["Artificial Grass", "Putting Greens", "Pet Turf", "Commercial", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass",
    "Putting Greens",
    "Pet Turf",
    "Commercial Turf",
    "Front Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "AGS",
  colors: {
    primary: "#5ba310",
    primaryDark: "#2b4d09",
    primarySoft: "#eef6e0",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 150,
    height: 40,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Artificial Grass Superstore prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Artificial Grass Superstore.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Artificial Grass Superstore review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Artificial Grass Superstore follows up with measurements, options, and final pricing",
    ],
  },
};
