import type { ClientConfig } from "../types";

export const bigBullyTurfClient: ClientConfig = {
  slug: "big-bully-turf",
  companyName: "Big Bully Turf",
  brandName: "BIG BULLY TURF",
  legalName: "Big Bully Turf",
  serviceLabel: "Artificial Grass",
  positioning: "Scottsdale artificial grass installer leaning on free consultations and eco-friendly, low-maintenance lawn benefits.",
  website: "https://bigbullyturf.com/",
  logoPath: "/images/big-bully-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 400-1090",
  email: "hello@bigbullyturf.com",
  navLinks: ["Artificial Grass", "Pet Turf", "Consultations", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass",
    "Pet Turf",
    "Residential Turf",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "BB",
  colors: {
    primary: "#0a9b6f",
    primaryDark: "#0c3b2d",
    primarySoft: "#e2f4ee",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Big Bully Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Big Bully Turf.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Big Bully Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Big Bully Turf follows up with measurements, options, and final pricing",
    ],
  },
};
