import type { ClientConfig } from "../types";

export const celebrityGreensMesaClient: ClientConfig = {
  slug: "celebrity-greens-mesa",
  companyName: "Celebrity Greens Mesa",
  brandName: "CELEBRITY GREENS MESA",
  legalName: "Celebrity Greens Mesa",
  serviceLabel: "Artificial Grass & Golf Greens",
  positioning: "Mesa artificial grass dealer-installer with premium golf-green branding and broad East Valley service coverage.",
  website: "https://www.celebritygreens.com/mesa/",
  logoPath: "/images/celebrity-greens-mesa-logo.webp",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "480-666-0288",
  email: "mesa@celebritygreens.com",
  navLinks: ["Artificial Grass", "Golf Greens", "Landscape Design", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass",
    "Golf Greens",
    "Landscape Design",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Putting Green",
    "Front Yard",
    "Back Yard",
    "Full Landscaping",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Putting Green": [4000, 11000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Full Landscaping": "review",
    Other: "review",
  },
  estimatePrefix: "CG",
  colors: {
    primary: "#1f5c34",
    primaryDark: "#0e2a18",
    primarySoft: "#e9f0ea",
    accent: "#b89a3e",
    accentDark: "#836c22",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 50,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass & Golf Greens Project Preview",
    contactPrompt: "Where should Celebrity Greens Mesa prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Celebrity Greens Mesa.",
    specialistLabel: "Artificial Grass & Golf Greens Specialists",
    reviewRequired: "This selection needs a Celebrity Greens Mesa review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Celebrity Greens Mesa follows up with measurements, options, and final pricing",
    ],
  },
};
