import type { ClientConfig } from "../types";

export const chandlerArtificialGrassClient: ClientConfig = {
  slug: "chandler-artificial-grass",
  companyName: "Chandler Artificial Grass",
  brandName: "CHANDLER ARTIFICIAL GRASS",
  legalName: "Chandler Artificial Grass",
  serviceLabel: "Artificial Grass",
  positioning: "Chandler turf installer leaning on licensed-and-insured credibility, affordability, and free-quote conversion language.",
  website: "https://www.chandlerartificialgrass.com/",
  logoPath: "/images/chandler-artificial-grass-logo.webp",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 780-3970",
  email: "info@chandlerartificialgrass.com",
  navLinks: ["Artificial Lawns", "Pet Turf", "Putting Greens", "Free Quotes", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Pet-Friendly Turf",
    "Putting Greens",
    "Artificial Lawns",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "CA",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#183820",
    primarySoft: "#e7f1e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 150,
    height: 32,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Chandler Artificial Grass prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Chandler Artificial Grass.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Chandler Artificial Grass review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Chandler Artificial Grass follows up with measurements, options, and final pricing",
    ],
  },
};
