import type { ClientConfig } from "../types";

export const diamondStoneSyntheticGrassClient: ClientConfig = {
  slug: "diamond-stone-synthetic-grass",
  companyName: "Diamond Stone & Synthetic Grass",
  brandName: "DIAMOND STONE & SYNTHETIC GRASS",
  legalName: "Diamond Stone & Synthetic Grass",
  serviceLabel: "Synthetic Grass & Stone",
  positioning: "Valley landscape construction company combining synthetic grass, stonework, design, and financing-style estimate messaging.",
  website: "https://dssggogreen.com/",
  logoPath: "/images/diamond-stone-synthetic-grass-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(623) 293-0396",
  email: "info@dssggogreen.com",
  navLinks: ["Synthetic Grass", "Stonework", "Landscape Design", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Synthetic Grass Installation",
    "Stonework",
    "Landscape Design",
    "Pavers",
    "Front Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Full Landscaping",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Full Landscaping": "review",
    Other: "review",
  },
  estimatePrefix: "DS",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#14302a",
    primarySoft: "#e7f1ee",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 34,
  },
  copy: {
    pageTitle: "Get Your Instant Synthetic Grass & Stone Project Preview",
    contactPrompt: "Where should Diamond Stone & Synthetic Grass prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Diamond Stone & Synthetic Grass.",
    specialistLabel: "Synthetic Grass & Stone Specialists",
    reviewRequired: "This selection needs a Diamond Stone & Synthetic Grass review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Diamond Stone & Synthetic Grass follows up with measurements, options, and final pricing",
    ],
  },
};
