import type { ClientConfig } from "../types";

export const durableLawnClient: ClientConfig = {
  slug: "durable-lawn",
  companyName: "Durable Lawn",
  brandName: "DURABLE LAWN",
  legalName: "Durable Lawn",
  serviceLabel: "Artificial Turf",
  positioning: "Artificial turf installer focused on durable, low-maintenance lawns for front yards, back yards, pets, and putting greens.",
  website: "https://www.durablelawn.com/",
  logoPath: "/images/durable-lawn-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "",
  email: "info@durablelawn.com",
  navLinks: ["Artificial Turf", "Pet Turf", "Putting Greens", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Pet Turf",
    "Putting Greens",
    "Front Yard Turf",
    "Back Yard Turf",
    "Pavers",
  ],
  projectOptions: [
    "Front Yard",
    "Back Yard",
    "Putting Green",
    "Pet Turf",
    "Pavers",
    "Decorative Rock",
    "Other",
  ],
  estimateRanges: {
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Putting Green": [3500, 9000],
    "Pet Turf": [5500, 15000],
    Pavers: [6000, 18000],
    "Decorative Rock": [2500, 8000],
    Other: "review",
  },
  estimatePrefix: "DL",
  colors: {
    primary: "#2f8f3a",
    primaryDark: "#163a1b",
    primarySoft: "#e9f4e8",
    accent: "#e0bf3a",
    accentDark: "#a8901f",
  },
  pdfLogo: {
    background: "none",
    width: 60,
    height: 58,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should Durable Lawn prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Durable Lawn.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a Durable Lawn review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Durable Lawn follows up with measurements, options, and final pricing",
    ],
  },
};
