import type { ClientConfig } from "../types";

export const eastValleyTurfClient: ClientConfig = {
  slug: "east-valley-turf",
  companyName: "East Valley Turf",
  brandName: "EAST VALLEY TURF",
  legalName: "East Valley Turf",
  serviceLabel: "Artificial Turf",
  positioning: "East Valley turf installer emphasizing honest pricing, long installation experience, and premium American-made products.",
  website: "https://www.eastvalleyturf.com/",
  logoPath: "/images/east-valley-turf-logo.webp",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "480-300-7292",
  email: "info@eastvalleyturf.com",
  navLinks: ["Artificial Turf", "Putting Greens", "Pet Turf", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Putting Greens",
    "Pet Turf",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "EV",
  colors: {
    primary: "#3f8a2a",
    primaryDark: "#16320c",
    primarySoft: "#eaf3e3",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should East Valley Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing East Valley Turf.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a East Valley Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "East Valley Turf follows up with measurements, options, and final pricing",
    ],
  },
};
