import type { ClientConfig } from "../types";

export const frdmTurfClient: ClientConfig = {
  slug: "frdm-turf",
  companyName: "FRDM Turf",
  brandName: "FRDM",
  legalName: "FRDM Turf",
  serviceLabel: "Artificial Turf",
  positioning: "Artificial turf installer for clean, low-maintenance lawns, putting greens, and pet-friendly yards.",
  website: "https://www.frdmturf.com/",
  logoPath: "/images/frdm-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(801) 214-1640",
  email: "info@frdmturf.com",
  navLinks: ["Artificial Turf", "Putting Greens", "Pet Turf", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Putting Greens",
    "Pet Turf",
    "Front Yard Turf",
    "Back Yard Turf",
    "Pavers",
  ],
  projectOptions: [
    "Front Yard",
    "Back Yard",
    "Putting Green",
    "Pet Turf",
    "Pavers",
    "Decorative Rock",
    "Other",
  ],
  estimateRanges: {
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Putting Green": [3500, 9000],
    "Pet Turf": [5500, 15000],
    Pavers: [6000, 18000],
    "Decorative Rock": [2500, 8000],
    Other: "review",
  },
  estimatePrefix: "FR",
  colors: {
    primary: "#5f8c50",
    primaryDark: "#314126",
    primarySoft: "#eef3ea",
    accent: "#b7d1ab",
    accentDark: "#8aa87b",
  },
  pdfLogo: {
    background: "dark",
    width: 160,
    height: 22,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should FRDM Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing FRDM Turf.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a FRDM Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "FRDM Turf follows up with measurements, options, and final pricing",
    ],
  },
};
