import type { ClientConfig } from "../types";

export const golfGreensAzClient: ClientConfig = {
  slug: "golf-greens-az",
  companyName: "Golf Greens AZ",
  brandName: "GOLF GREENS AZ",
  legalName: "Golf Greens AZ",
  serviceLabel: "Putting Greens",
  positioning: "Phoenix-area locally owned installer centered on putting greens, turf, and pavers with a personal small-shop sales feel.",
  website: "https://golfgreensaz.com/",
  logoPath: "/images/golf-greens-az-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 329-8820",
  email: "azgolfgreens@gmail.com",
  navLinks: ["Putting Greens", "Artificial Turf", "Pavers", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Putting Greens",
    "Artificial Turf",
    "Pavers",
    "Front Yard Turf",
    "Back Yard Turf",
  ],
  projectOptions: [
    "Putting Green",
    "Artificial Grass",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Putting Green": [4000, 11000],
    "Artificial Grass": [5000, 14500],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "GG",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#183820",
    primarySoft: "#e7f1e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 45,
  },
  copy: {
    pageTitle: "Get Your Instant Putting Greens Project Preview",
    contactPrompt: "Where should Golf Greens AZ prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Golf Greens AZ.",
    specialistLabel: "Putting Greens Specialists",
    reviewRequired: "This selection needs a Golf Greens AZ review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Golf Greens AZ follows up with measurements, options, and final pricing",
    ],
  },
};
