import type { ClientConfig } from "../types";

export const hotshotPoolsClient: ClientConfig = {
  slug: "hotshot-pools",
  companyName: "Hotshot Hardscape and Pools",
  brandName: "HOTSHOT HARDSCAPE & POOLS",
  legalName: "Hotshot Hardscape and Pools",
  serviceLabel: "Hardscape & Pools",
  positioning: "Arizona hardscape and pool builder for travertine pavers, pool decks, outdoor kitchens, fire pits, and full backyard transformations.",
  website: "https://hotshotpools.com/",
  logoPath: "/images/hotshot-pools-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(623) 231-7547",
  email: "info@hotshotpools.com",
  navLinks: ["Pools", "Hardscape", "Outdoor Living", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Pool Decks & Decking",
    "Travertine & Pavers",
    "Outdoor Kitchens",
    "Fire Pits",
    "Artificial Turf",
    "Decorative Rock",
  ],
  projectOptions: [
    "Pavers & Hardscape",
    "Pool Deck",
    "Outdoor Kitchen",
    "Fire Pit",
    "Artificial Turf",
    "Decorative Rock",
    "Pool Build / Remodel",
    "Other",
  ],
  estimateRanges: {
    "Pavers & Hardscape": [6000, 20000],
    "Pool Deck": [8000, 24000],
    "Outdoor Kitchen": "review",
    "Fire Pit": [2500, 9000],
    "Artificial Turf": [5000, 14000],
    "Decorative Rock": [2500, 8000],
    "Pool Build / Remodel": "review",
    Other: "review",
  },
  estimatePrefix: "HS",
  colors: {
    primary: "#1f8aa8",
    primaryDark: "#123c49",
    primarySoft: "#e6f2f6",
    accent: "#d97b3a",
    accentDark: "#a8551f",
  },
  pdfLogo: {
    background: "dark",
    width: 132,
    height: 87,
  },
  copy: {
    pageTitle: "Get Your Instant Backyard & Pool Project Preview",
    contactPrompt: "Where should Hotshot prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about the pool, decking, pavers, outdoor kitchen, access, timing, or the look you want.",
    generateButton: "Generate Backyard Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Hotshot Hardscape and Pools.",
    specialistLabel: "Hardscape & Pool Specialists",
    reviewRequired: "This selection needs a Hotshot review before a range is shown.",
    nextSteps: [
      "We review your photos and selected project options",
      "Your backyard and pool concept preview is prepared",
      "Hotshot follows up with measurements, options, and final pricing",
    ],
  },
};
