import type { ClientConfig } from "../types";

export const masterazscapesClient: ClientConfig = {
  slug: "masterazscapes",
  companyName: "MasterAZscapes",
  brandName: "MASTERAZSCAPES",
  legalName: "MasterAZscapes LLC",
  serviceLabel: "Landscape Design",
  positioning: "Phoenix landscape designer with broad outdoor-transformation work including artificial turf, hardscape, and full yard remodels.",
  website: "https://www.landscaper-phoenix.com/",
  logoPath: "/images/masterazscapes-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(602) 975-3648",
  email: "info@landscaper-phoenix.com",
  navLinks: ["Landscape Design", "Artificial Turf", "Backyard Remodeling", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Landscape Design",
    "Artificial Turf",
    "Backyard Remodeling",
    "Retaining Walls",
    "Pavers",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Full Landscaping",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Full Landscaping": "review",
    Other: "review",
  },
  estimatePrefix: "MA",
  colors: {
    primary: "#2f7d43",
    primaryDark: "#183820",
    primarySoft: "#e7f1e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 120,
    height: 80,
  },
  copy: {
    pageTitle: "Get Your Instant Landscape Design Project Preview",
    contactPrompt: "Where should MasterAZscapes prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing MasterAZscapes.",
    specialistLabel: "Landscape Design Specialists",
    reviewRequired: "This selection needs a MasterAZscapes review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "MasterAZscapes follows up with measurements, options, and final pricing",
    ],
  },
};
