import type { ClientConfig } from "../types";

export const scottsdaleTurfClient: ClientConfig = {
  slug: "scottsdale-turf",
  companyName: "Scottsdale Turf",
  brandName: "SCOTTSDALE TURF",
  legalName: "Scottsdale Turf",
  serviceLabel: "Artificial Grass",
  positioning: "Top-rated Scottsdale artificial grass installer with pet-friendly turf, putting greens, and sports surface positioning.",
  website: "https://www.scottsdaleturf.com/",
  logoPath: "/images/scottsdale-turf-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 405-3667",
  email: "info@scottsdaleturf.com",
  navLinks: ["Artificial Grass", "Pet Turf", "Putting Greens", "Sports Turf", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass Lawns",
    "Pet-Friendly Turf",
    "Putting Greens",
    "Sports Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Sports Turf",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    "Sports Turf": [7000, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "ST",
  colors: {
    primary: "#1f7a3a",
    primaryDark: "#0d3d1c",
    primarySoft: "#e7f2e9",
    accent: "#c8a24a",
    accentDark: "#8a6e22",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Scottsdale Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Scottsdale Turf.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Scottsdale Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Scottsdale Turf follows up with measurements, options, and final pricing",
    ],
  },
};
