import type { ClientConfig } from "../types";

export const turfMesaClient: ClientConfig = {
  slug: "turf-mesa",
  companyName: "Turf Mesa",
  brandName: "TURF MESA",
  legalName: "Turf Mesa",
  serviceLabel: "Artificial Grass",
  positioning: "Mesa artificial grass and paver installer focused on lawns, pet turf, and backyard upgrades with free estimates.",
  website: "https://www.turfmesa.com/",
  logoPath: "/images/turf-mesa-logo.webp",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 745-2245",
  email: "info@turfmesa.com",
  navLinks: ["Artificial Lawns", "Pet Turf", "Putting Greens", "Pavers", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Lawns",
    "Pet-Friendly Turf",
    "Backyard Putting Greens",
    "Paver Installation",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Putting Green",
    "Pavers",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Putting Green": [4000, 11000],
    Pavers: [6500, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "TM",
  colors: {
    primary: "#2f7d3d",
    primaryDark: "#143620",
    primarySoft: "#e7f1e8",
    accent: "#c8a24a",
    accentDark: "#8a6e22",
  },
  pdfLogo: {
    background: "none",
    width: 150,
    height: 60,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Grass Project Preview",
    contactPrompt: "Where should Turf Mesa prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Turf Mesa.",
    specialistLabel: "Artificial Grass Specialists",
    reviewRequired: "This selection needs a Turf Mesa review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Turf Mesa follows up with measurements, options, and final pricing",
    ],
  },
};
