import type { ClientConfig } from "../types";

export const turfGilbertClient: ClientConfig = {
  slug: "turf-gilbert",
  companyName: "Turf Gilbert",
  brandName: "TURF GILBERT",
  legalName: "Turf Gilbert",
  serviceLabel: "Artificial Turf",
  positioning: "Gilbert artificial turf installer focused on trust, free estimates, and family-friendly turf applications across the East Valley.",
  website: "https://www.turfgilbert.com/",
  logoPath: "/images/turf-gilbert-logo.webp",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 470-8771",
  email: "info@turfgilbert.com",
  navLinks: ["Artificial Grass", "Pet Turf", "Playground Turf", "Sports Turf", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Grass Landscaping",
    "Pet Turf",
    "Playground Turf",
    "Sports Turf",
  ],
  projectOptions: [
    "Artificial Grass",
    "Pet Turf",
    "Playground Turf",
    "Sports Turf",
    "Front Yard",
    "Back Yard",
    "Other",
  ],
  estimateRanges: {
    "Artificial Grass": [5000, 14500],
    "Pet Turf": [5500, 15500],
    "Playground Turf": [7000, 19000],
    "Sports Turf": [7000, 19000],
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    Other: "review",
  },
  estimatePrefix: "TG",
  colors: {
    primary: "#3f8a2a",
    primaryDark: "#16320c",
    primarySoft: "#eaf3e3",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 150,
    height: 34,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should Turf Gilbert prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, pavers, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Turf Gilbert.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a Turf Gilbert review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Turf Gilbert follows up with measurements, options, and final pricing",
    ],
  },
};
