import type { ClientConfig } from "../types";

export const turfTimeArizonaClient: ClientConfig = {
  slug: "turf-time-arizona",
  companyName: "Turf Time Arizona",
  brandName: "TURF TIME ARIZONA",
  legalName: "Turf Time Arizona",
  serviceLabel: "Artificial Turf",
  positioning: "Arizona artificial turf installer for clean, low-maintenance front and back yards, putting greens, and pet-friendly lawns.",
  website: "https://www.turftimeaz.com/",
  logoPath: "/images/turf-time-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(480) 743-1063",
  email: "info@turftimeaz.com",
  navLinks: ["Artificial Turf", "Putting Greens", "Pet Turf", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Quote", "Contact"],
  services: [
    "Artificial Turf",
    "Putting Greens",
    "Pet Turf",
    "Front Yard Turf",
    "Back Yard Turf",
    "Pavers",
  ],
  projectOptions: [
    "Front Yard",
    "Back Yard",
    "Putting Green",
    "Pet Turf",
    "Pavers",
    "Decorative Rock",
    "Other",
  ],
  estimateRanges: {
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Putting Green": [3500, 9000],
    "Pet Turf": [5500, 15000],
    Pavers: [6000, 18000],
    "Decorative Rock": [2500, 8000],
    Other: "review",
  },
  estimatePrefix: "TT",
  colors: {
    primary: "#3aa935",
    primaryDark: "#163a1b",
    primarySoft: "#e9f4e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 58,
    height: 58,
  },
  copy: {
    pageTitle: "Get Your Instant Artificial Turf Project Preview",
    contactPrompt: "Where should Turf Time Arizona prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about pets, putting greens, drainage, access, timing, or the look you want.",
    generateButton: "Generate Turf Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Turf Time Arizona.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired: "This selection needs a Turf Time Arizona review before a range is shown.",
    nextSteps: [
      "We review your photos and selected turf options",
      "Your artificial turf concept preview is prepared",
      "Turf Time Arizona follows up with measurements, options, and final pricing",
    ],
  },
};
