import type { ClientConfig } from "../types";

export const twoGreenLandscapesClient: ClientConfig = {
  slug: "2green-landscapes",
  companyName: "2 Green Landscapes LLC",
  brandName: "2 GREEN LANDSCAPES",
  legalName: "2 Green Landscapes LLC",
  serviceLabel: "Landscaping",
  positioning: "New Mexico design, installation, maintenance, and home-repair landscaping team for full yard transformations.",
  website: "https://www.2greenlandscapes.com/",
  logoPath: "/images/2green-logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(505) 582-4187",
  email: "info@2greenlandscapes.com",
  navLinks: ["Design", "Installation", "Maintenance", "Contact"],
  quickLinks: ["Home", "Services", "Gallery", "Reviews", "Free Estimate", "Contact"],
  services: [
    "Landscape Design",
    "Artificial Turf",
    "Pavers & Hardscape",
    "Decorative Rock",
    "Front Yard Remodels",
    "Back Yard Remodels",
  ],
  projectOptions: [
    "Front Yard",
    "Back Yard",
    "Artificial Turf",
    "Pavers",
    "Decorative Rock",
    "Full Landscape Remodel",
    "Other",
  ],
  estimateRanges: {
    "Front Yard": [4500, 13000],
    "Back Yard": [5500, 15000],
    "Artificial Turf": [5000, 14000],
    Pavers: [6000, 18000],
    "Decorative Rock": [2500, 8000],
    "Full Landscape Remodel": "review",
    Other: "review",
  },
  estimatePrefix: "2G",
  colors: {
    primary: "#39a23a",
    primaryDark: "#143a17",
    primarySoft: "#e8f3e8",
    accent: "#d7ad3b",
    accentDark: "#92711c",
  },
  pdfLogo: {
    background: "dark",
    width: 150,
    height: 71,
  },
  copy: {
    pageTitle: "Get Your Instant Landscape Project Preview",
    contactPrompt: "Where should 2 Green Landscapes prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about access, drainage, pets, timing, materials, or the look you want.",
    generateButton: "Generate Landscape Project Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing 2 Green Landscapes.",
    specialistLabel: "Landscape Design Specialists",
    reviewRequired: "This selection needs a 2 Green Landscapes review before a range is shown.",
    nextSteps: [
      "We review your photos and selected landscape options",
      "Your landscape concept preview is prepared",
      "2 Green Landscapes follows up with measurements, options, and final pricing",
    ],
  },
};
