import type { ClientConfig } from "../types";

export const waterlooClient: ClientConfig = {
  slug: "waterloo",
  companyName: "Waterloo Turf",
  brandName: "WATERLOO TURF",
  legalName: "Waterloo Turf Franchising Co, LLC.",
  serviceLabel: "Artificial Turf",
  positioning: "Artificial turf specialists for residential and commercial spaces.",
  website: "https://waterlooturf.com/",
  logoPath: "/images/logo.png",
  footerImagePath: "/images/footer-turf-premium.png",
  phone: "(512) 607-9335",
  email: "info@waterlooturf.com",
  navLinks: ["About Us", "Services", "Gallery", "Blog", "Merch", "Own a Franchise"],
  quickLinks: [
    "Home",
    "Locations",
    "About Us",
    "Gallery",
    "Blog",
    "Franchise",
    "Merch",
    "Terms & Conditions",
  ],
  services: [
    "Front & Back Yards",
    "Pet Turf",
    "Putting Greens",
    "Playground Turf",
    "Commercial",
    "Sports Turf",
  ],
  projectOptions: [
    "Front Yard",
    "Back Yard",
    "Sports Turf",
    "Commercial",
    "Putting Green",
    "Other",
  ],
  estimateRanges: {
    "Front Yard": [4500, 9500],
    "Back Yard": [5500, 12500],
    "Sports Turf": [8000, 20000],
    Commercial: [10000, 35000],
    "Putting Green": [3500, 9000],
    Other: "review",
  },
  estimatePrefix: "WT",
  colors: {
    primary: "#2e8050",
    primaryDark: "#183820",
    primarySoft: "#e4f0df",
    accent: "#e4b83d",
    accentDark: "#b88c16",
  },
  copy: {
    pageTitle: "Fill Out The Form Below To Schedule Your Free Onsite Estimate",
    contactPrompt: "Where should Waterloo Turf prepare this preview?",
    notesPlaceholder:
      "Tell us anything helpful about access, timing, slope, drainage, or the look you want.",
    generateButton: "Generate AI Yard Preview",
    pdfTitle: "AI VISUAL ESTIMATE",
    pdfThanks: "Thank you for choosing Waterloo Turf.",
    specialistLabel: "Artificial Turf Specialists",
    reviewRequired:
      "This selection needs a Waterloo Turf review before a range is shown.",
    nextSteps: [
      "We review your photos and project details",
      "Your AI concept preview is prepared",
      "Waterloo Turf follows up with next steps and pricing",
    ],
  },
};
